### ISSUE TITLE
Doesn't work when Wi-Fi is enabled

### ISSUE THREAD

**Issue by nikclayton** [barsanuphe/librariansync#6]
LibrarianSync doesn't appear to work when Wi-Fi is enabled. I can't find this fact documented anywhere in the LibrarianSync documentation.

Symptom is that if you try and use it with Wi-Fi enabled from the KUAL menu you get the "something went very wrong" message, with a log entry that looks like:

```
61120:182251 system: I LibrarianSync:main:: Starting...
161120:182251 system: I LibrarianSync:rebuild_from_calibre_plugin_json:: Rebuilding collections (Calibre)...
161120:182251 system: I LibrarianSync:cc_update:: Sending commands...
161120:182252 system: E LibrarianSync:main:: Something went very wrong.
```

So I enabled USB networking on the device and went poking around.  

```shell
/mnt/us/extensions/librariansync% ./generate_collections.py --rebuild-calibre
Traceback (most recent call last):
  File "./generate_collections.py", line 323, in <module>
    source="calibre_plugin")
  File "./generate_collections.py", line 233, in update_cc_db
    cc.execute()
  File "/mnt/us/extensions/librariansync/cc_update.py", line 105, in execute
    headers={'content-type': 'application/json'})
  File "/mnt/us/python/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/mnt/us/python/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/mnt/us/python/lib/python2.7/site-packages/requests/sessions.py", line 477, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/us/python/lib/python2.7/site-packages/requests/sessions.py", line 587, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/us/python/lib/python2.7/site-packages/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9101): Max retries exceeded with url: /change (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x427eced0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

(as an aside, it would be really helpful if that was dumped in to the log).

The only thing I've found that might be relevant is  http://wiki.mobileread.com/wiki/Kindle_Touch_Hacking which has a throwaway comment in it that says:

"Also note that this will only work as long as you NEVER turn on network connectivity on the Kindle."

although that appears in a block of text talking about unregistered devices, and my device is registered.

If I enable airplane mode and re-run the command (or run it from KUAL) it works.

**Comment by barsanuphe** [comment]
That is strange. LibrarianSync needs to connect to a local service (http://localhost:9101), which should be there with Wi-Fi off or on.

**Comment by nikclayton** [comment]
I can reproduce this 100%, on my Voyage with Firmware 5.8.5.0.2 (3085210002).

I followed the steps at http://www.mobileread.com/forums/showthread.php?t=275877 to jailbreak.

Then installed KUAL (from KUAL-v2.7.zip, identifies itself when installed as v2.7 (2016021,a)).

Then installed the python 0.14, linkss-0.24N, and librariansync-1.10 packages from the mobileread threads. linkss is working (i.e., I have working custom screensavers, so I assume there is no problem with the jailbreak).

Used the Calibre plugin to generate a collections.json file on the device, and discovered that librariansync was generating the error.

After some wrong turns investigating the structure of the JSON file, and looking at the generate_collections.py code to figure out what it was doing, I followed the instructions at http://wiki.mobileread.com/wiki/Kindle_Touch_Hacking#USB_Networking to install the USB package and ssh in to the device (over USB), where I was able to run the `generate_collections.py` command from the initial post and see the error.

Going in to airplane mode and re-running the command and it runs successfully (and from KUAL).

Disabling airplane mode, and waiting a few seconds and it repeatedly fails.

I've got 2,549 MB free on the device at the moment, so I assume space is not an issue.

In airplane mode, if I check to see what's listening on 9101, I see

```shell
% lsof | grep 9101
cvm       15813  framework  278u  IPv4      55641      0t0        TCP 127.0.0.1:9101 (LISTEN)
```

If I turn off airplane mode and re-run that, it's still there.

**Comment by zeflash** [comment]
Ah! After spending a couple of hours trying to figure out why it wasn't working for me I finally found the answer :)

Paperwhite 3 (G090 KB), FW 5.8.7. Did all the steps previously mentioned, JB, KUAL, python, librarianSync. 

Same symptoms: the "sending command" step would take forever after finally giving up with the "something went very wrong" error.

Going into airplane mode fixed the issue for me too.

**Comment by NiLuJe** [comment]
The best (?) explanation I can come up with is that when WiFi's on, everything goes through Amazon's magical WhisperSync proxy, and that royally mangles things?

One stupid thing to try would be replacing localhost by 127.0.0.1 and see what happens...

**Comment by NiLuJe** [comment]
Got confirmation that #10 fixes it ;).
